spring:
  application:
    name: auth-service

server:
  servlet:
    context-path: /api/v1

security:
  jwt:
    expiration-in-minutes: 30
    secret-key: bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3OCBhYmNkZWZn